### ISSUE TITLE
실제 데이터 문자열 데이터 처리

### ISSUE THREAD

**Issue by NDjust** [DSC-SCH/Determination-of-the-Status-of-Nuclear-Power-Plants#3]
지난번에 on / off 문자열과 관련한 이슈가 있다고 했는데, 나머지 문자열 관련해서도 단순히 레이블 인코딩으로 처리하는 것이 아니라 아예 행을 제거하는 방안도 고려 해봐야 할까요??

아니면 현재 실제 데이터와 모사데이터 비율 차이가 너무 심하니 아예 모사 데이터로만 모델링을 진행을 해보는건 어떨까요?

**Comment by parkseonga** [comment]
컬럼 자체를 제거하고 하는 것도 좋은 방안 같아요!

실제 데이터를 포함시킨 후 컬럼 자체를 제거하는 등의 방안으로 on/off 와 같은 문자열을 처리하고 실제데이터(30.csv)를 제외한 모사 데이터로만으로도 모델링을 진행해보아요!!
