### ISSUE TITLE
PCA Dimension size Selection

### ISSUE THREAD

**Issue by NDjust** [DSC-SCH/Determination-of-the-Status-of-Nuclear-Power-Plants#5]
PCA Feature Dimension size를 어떻게 가져가야 할까요?

01/22일자 기준 1000개로 진행한 후 시각화 해봤는데, 약간 애매한거 같네요! 

그리고 pca 진행 후 검토 사항 같은게 있다면, 피드백 부탁드릴게요.

pca나 이런 시계열 데이터는 처음인지라 감이 잘 안잡히네요 😢

**Comment by parkseonga** [comment]
PCA  진행 시 분산의 설명력을 99% 갖도록 설정했더니 딱 1000개, 95% 갖도록 설정했을 때 633개 정도 나와서 1000개 정도면 괜찮지 않을까 생각이 들어요! 시각화는 너무 어렵네요 😢

제 노트북에서는 PCA가 데이터를 조금 줄여서 불러왔는데도 메모리를 너무 많이 잡아먹어서 한 번 실행하고 나면 다른 모델을 돌리지 못하게 되네요ㅠㅠ  IncremenalPCA를 이용해서 메모리 용량을 조금이라도 줄이는 방안을 고려하는 것도 좋을 것 같아요!!

해당 코드는 올려놓겠습니다.
